Update grade.py
teodutu/Scripts pull request #3
Opened 2022-03-15 20:13 UTC by gabrielmocanu

Change the logic for ungraded students and fix a typo. Now all the grades for all students are required to be in the attendance list.

Signed-off-by: Gabriel Mocanu <gabi.mocanu98@gmail.com>

2022-03-17 14:45 UTC, teodutu requested changes
Nice error handling. I made a few suggestions. After they're addressed, the PR is good to go.

2022-03-17 14:45 UTC, teodutu commented on lab-grading/grade.py
> +        ungraded_students = list(filter(lambda s: len(s) < 2, students_lab))
```suggestion
        ungraded_students = any(lambda s: len(s) < 2, students_lab)
```

2022-03-17 14:45 UTC, teodutu commented on lab-grading/grade.py
> +        if(len(ungraded_students) >= 1):
```suggestion
        if ungraded_students:
```

2022-03-17 14:45 UTC, teodutu commented on lab-grading/grade.py
> +            print("You have at least one student that it's not graded in attendance list. Please grade all students before run the script.")
Split this on multiple lines so that they don't exceed 80 chars.

2022-03-17 14:45 UTC, teodutu commented on lab-grading/grade.py
> +        else:
This `else` is useless due to the `return` above.

2022-03-17 19:57 UTC, gabrielmocanu commented on lab-grading/grade.py
> +        else:
It's not useless because if it wouldn't be there it would print for every student the same message.

2022-03-17 20:00 UTC, gabrielmocanu commented on lab-grading/grade.py
> +        ungraded_students = list(filter(lambda s: len(s) < 2, students_lab))
You fooled me with this one.
`any` returns True/False and there I need a list to be returned. Do you have a better idea? Or do other versions of python have a different implementation of `any`?

2022-03-17 20:02 UTC, gabrielmocanu commented on lab-grading/grade.py
> +            print("You have at least one student that it's not graded in attendance list. Please grade all students before run the script.")
Done.

2022-03-17 21:55 UTC, teodutu commented on lab-grading/grade.py
> +        ungraded_students = list(filter(lambda s: len(s) < 2, students_lab))
Why do you need a list? As far as I can see, you're only using it to check if it contains any elements, i.e. to check if any lists in `students_lab` contain less than 2 elements. Using `any`, you'll be evaluating `ungraded_students` as a boolean variable on line 146 with the same functionality as now.

2022-03-17 22:00 UTC, teodutu commented on lab-grading/grade.py
> +        else:
No. You have a `return` statement on the line above this `else`. The `return` statement would terminate `main` altogether, so only one message will be printed.

2022-03-17 23:54 UTC, gabrielmocanu commented on lab-grading/grade.py
> +        else:
My bad. I thought you were saying to remove the return.
You're right about this one. I will make the change.

2022-03-17 23:55 UTC, gabrielmocanu commented on lab-grading/grade.py
> +        ungraded_students = list(filter(lambda s: len(s) < 2, students_lab))
Silly me. I just took your change, I saw it didn't work and I didn't think about it.
That any needs a map before with that lambda function and `students_lab`.
I will make the changes asap.

2022-03-17 23:59 UTC, gabrielmocanu commented on lab-grading/grade.py
> +        ungraded_students = list(filter(lambda s: len(s) < 2, students_lab))
@teodutu  Done. Please have a look now.

2022-03-17 23:59 UTC, gabrielmocanu commented on lab-grading/grade.py
> +        else:
@teodutu  Done. Please have a look now.

2022-03-18 06:07 UTC, teodutu approved these changes
It's alright now. Thanks!

2022-03-20 06:44 UTC, merged